name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build APK with Buildozer Action
      uses: ArtemSundaev/buildozer-action@v1
      with:
        workdir: .
        buildozer_version: master

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Sakina-Prayer-App
        path: bin/*.apk
